#!/bin/sh
# -*- shell-script; -*-

FILE=$1
C_SOURCE=${FILE%.el}.c
C_HEADER=${FILE%.el}.h

EVAL="
(progn
  (setq load-path (append  '(\".\" \"/usr/local/share/emacs/site-lisp\") load-path)) 
  (load \"gen-main\")
  (load \"$FILE\")
  (gen-main-write  opt-list \"$C_SOURCE\" \"$C_HEADER\"))
"

#echo $EVAL

exec emacs -batch  --eval="$EVAL"
